version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dump.sql:/dump.sql
  db-test:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dump.sql:/dump.sql



# docker-compose up -d
# psql -U postgres -d postgres -a -f dump.sql